// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardsComponent: typeof import('./src/components/home/CardsComponent.vue')['default']
    ConfrontationComponent: typeof import('./src/components/home/ConfrontationComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    ParallaxComponent: typeof import('./src/components/home/ParallaxComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderComponent: typeof import('./src/components/home/SliderComponent.vue')['default']
    WaifuCards: typeof import('./src/components/waifu/WaifuCards.vue')['default']
    WaifuMore: typeof import('./src/components/waifu/WaifuMore.vue')['default']
  }
}
