// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cards: typeof import('./src/components/home/cards.vue')['default']
    Confrontation: typeof import('./src/components/home/confrontation.vue')['default']
    Drawer: typeof import('./src/components/drawer.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HeaderComponentOld: typeof import('./src/components/HeaderComponentOld.vue')['default']
    LanguageDrop: typeof import('./src/components/LanguageDrop.vue')['default']
    Parallax: typeof import('./src/components/home/parallax.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/home/slider.vue')['default']
    Snackbar: typeof import('./src/components/snackbar.vue')['default']
    WaifuCards: typeof import('./src/components/waifu/WaifuCards.vue')['default']
    WaifuMore: typeof import('./src/components/waifu/WaifuMore.vue')['default']
  }
}
